// Full copied script for standalone multi-group manager
// (Synchronized snapshot from root on 2025-11-01)
// Expense Splitter JavaScript

class LocalFileStorage {
	constructor() {
		this.directoryHandle = null;
		this.fileHandle = null;
		this.isSupported = 'showDirectoryPicker' in window;
		this.dataFileName = 'expense_splitter_data.json';
	}
	async chooseDirectory() { if (!this.isSupported) throw new Error('File System Access API not supported in this browser'); try { this.directoryHandle = await window.showDirectoryPicker({ mode: 'readwrite' }); await this.ensureDataFile(); return true; } catch (error) { if (error.name !== 'AbortError') { console.error('Error choosing directory:', error); throw error; } return false; } }
	async ensureDataFile() { if (!this.directoryHandle) return; try { this.fileHandle = await this.directoryHandle.getFileHandle(this.dataFileName); } catch (error) { if (error.name === 'NotFoundError') { this.fileHandle = await this.directoryHandle.getFileHandle(this.dataFileName, { create: true }); await this.saveData({ groups: [], friends: [], expenses: [], settlements: [], currentGroupId: 'default', metadata: { version: '2.0', created: new Date().toISOString(), lastModified: new Date().toISOString() } }); } else { throw error; } } }
	async saveData(data) { if (!this.fileHandle) throw new Error('No file selected. Please choose a folder first.'); try { data.metadata = { ...data.metadata, lastModified: new Date().toISOString(), version: '2.0' }; const writable = await this.fileHandle.createWritable(); await writable.write(JSON.stringify(data, null, 2)); await writable.close(); return true; } catch (error) { console.error('Error saving data:', error); throw error; } }
	async loadData() { if (!this.fileHandle) throw new Error('No file selected. Please choose a folder first.'); try { const file = await this.fileHandle.getFile(); const text = await file.text(); return JSON.parse(text); } catch (error) { console.error('Error loading data:', error); throw error; } }
	async createBackup() { if (!this.directoryHandle || !this.fileHandle) return; try { const data = await this.loadData(); const timestamp = new Date().toISOString().replace(/[:.]/g, '-'); const backupFileName = `expense_splitter_backup_${timestamp}.json`; const backupHandle = await this.directoryHandle.getFileHandle(backupFileName, { create: true }); const writable = await backupHandle.createWritable(); await writable.write(JSON.stringify(data, null, 2)); await writable.close(); return backupFileName; } catch (error) { console.error('Error creating backup:', error); } }
	getStoragePath() { return this.directoryHandle ? this.directoryHandle.name : null; }
	isReady() { return this.directoryHandle && this.fileHandle; }
}

class ExpenseSplitter { /* simplified inline copy of full class for brevity in folder (see root original for expanded comments) */
	constructor() { this.groups=[];this.friends=[];this.expenses=[];this.settlements=[];this.currentGroupId='default';this.fileStorage=new LocalFileStorage();this.autoSaveEnabled=true;this.lastSaveTime=null;this.initializeApp();this.loadFromStorage(); }
	initializeApp(){ this.setupEventListeners();this.checkBrowserCompatibility();this.ensureDefaultGroup();this.updateStorageUI();this.displayGroups();this.updateGroupStats();this.setTodayDate();this.displayFriends();this.updatePaidByOptions();this.updateGroupOptions();this.displayExpenses();this.updateBalanceSummary();this.updateSettlementSuggestions();this.updateSplitDetails(); }
	checkBrowserCompatibility(){const w=document.getElementById('compatibility-warning');const btn=document.getElementById('choose-folder-btn');if(!this.fileStorage.isSupported){w.classList.remove('hidden');btn.disabled=true;btn.innerHTML='<i class="fas fa-times"></i> Not Supported';btn.title='File System Access API not supported in this browser';}}
	async chooseFolderLocation(){try{const success=await this.fileStorage.chooseDirectory();if(success){this.updateStorageUI();try{await this.loadFromFile();}catch{console.log('No existing data found, starting fresh');this.saveToFile();}this.showNotification('Storage location selected successfully!','success');}}catch(error){console.error('Error choosing folder:',error);if(error.message.includes('not supported')){this.showNotification('File storage not supported in this browser. Try Chrome/Edge.','error');}else{this.showNotification('Error selecting folder location','error');}}}
	async saveToFile(){if(!this.fileStorage.isReady()){this.showNotification('Please choose a folder location first','error');return;}try{const data={groups:this.groups,friends:this.friends,expenses:this.expenses,settlements:this.settlements,currentGroupId:this.currentGroupId};await this.fileStorage.saveData(data);this.lastSaveTime=new Date();this.updateStorageUI();if(!this.autoSaveEnabled){this.showNotification('Data saved successfully!','success');}}catch(e){console.error('Error saving to file:',e);this.showNotification('Error saving data to file','error');}}
	async loadFromFile(){if(!this.fileStorage.isReady()){this.showNotification('Please choose a folder location first','error');return;}try{const data=await this.fileStorage.loadData();if(data){this.groups=data.groups||[];this.friends=data.friends||[];this.expenses=data.expenses||[];this.settlements=data.settlements||[];this.currentGroupId=data.currentGroupId||'default';this.expenses.forEach(e=>{e.date=new Date(e.date);e.createdAt=new Date(e.createdAt);});this.settlements.forEach(s=>{s.date=new Date(s.date);s.createdAt=new Date(s.createdAt);});this.friends.forEach(f=>{f.createdAt=new Date(f.createdAt);});this.groups.forEach(g=>{g.createdAt=new Date(g.createdAt);});this.ensureDefaultGroup();this.displayGroups();this.updateGroupStats();this.displayFriends();this.updatePaidByOptions();this.updateGroupOptions();this.displayExpenses();this.updateBalanceSummary();this.updateSettlementSuggestions();this.updateSplitDetails();this.showNotification('Data loaded successfully!','success');}}catch(e){console.error('Error loading from file:',e);this.showNotification('Error loading data from file','error');}}
	updateStorageUI(){const status=document.getElementById('storage-status');const path=document.getElementById('storage-path');const saveBtn=document.getElementById('save-data-btn');const lastSave=document.getElementById('last-save-time');const auto=document.getElementById('auto-save-toggle');if(this.fileStorage.isReady()){status.textContent='✅';path.textContent=`Saving to: ${this.fileStorage.getStoragePath()}/${this.fileStorage.dataFileName}`;saveBtn.disabled=false;}else{status.textContent='📁';path.textContent='Click "Choose Folder" to select where to save your data';saveBtn.disabled=true;}auto.checked=this.autoSaveEnabled;lastSave.textContent=this.lastSaveTime?this.lastSaveTime.toLocaleString():'Never';}
	ensureDefaultGroup(){if(!this.groups.find(g=>g.id==='default')){this.groups.unshift({id:'default',name:'Default Group',createdAt:new Date(),description:'Default group for general expenses'});}}
	addGroup(){const nameInput=document.getElementById('new-group-name');const name=nameInput.value.trim();if(!name){this.showNotification('Please enter a group/trip name','error');return;}if(this.groups.some(g=>g.name.toLowerCase()===name.toLowerCase())){this.showNotification('Group name already exists','error');return;}const group={id:Date.now().toString(),name,createdAt:new Date(),description:`Group created for ${name}`};this.groups.push(group);this.saveToStorage();nameInput.value='';this.displayGroups();this.switchGroup(group.id);this.showNotification(`Group "${name}" created successfully!`,'success');}
	switchGroup(id){this.currentGroupId=id;this.displayGroups();this.updateGroupStats();this.displayFriends();this.updatePaidByOptions();this.updateGroupOptions();this.displayExpenses();this.updateBalanceSummary();this.updateSettlementSuggestions();this.updateSplitDetails();this.saveToStorage();}
	deleteCurrentGroup(){if(this.currentGroupId==='default'){this.showNotification('Cannot delete the default group','error');return;}const currentGroup=this.groups.find(g=>g.id===this.currentGroupId);if(!currentGroup)return;const groupExpenses=this.expenses.filter(e=>e.groupId===this.currentGroupId);if(groupExpenses.length>0){this.showNotification('Cannot delete group with existing expenses','error');return;}if(confirm(`Delete group "${currentGroup.name}"? This action cannot be undone.`)){this.groups=this.groups.filter(g=>g.id!==this.currentGroupId);this.currentGroupId='default';this.saveToStorage();this.switchGroup('default');this.showNotification(`Group "${currentGroup.name}" deleted successfully!`,'success');}}
	displayGroups(){const sel=document.getElementById('group-selector');sel.innerHTML='';this.groups.forEach(g=>{const o=document.createElement('option');o.value=g.id;o.textContent=g.name;sel.appendChild(o);});sel.value=this.currentGroupId;const del=document.getElementById('delete-group-btn');del.disabled=this.currentGroupId==='default';del.style.opacity=this.currentGroupId==='default'?'0.5':'1';}
	updateGroupOptions(){const s=document.getElementById('expense-group');s.innerHTML='';this.groups.forEach(g=>{const o=document.createElement('option');o.value=g.id;o.textContent=g.name;s.appendChild(o);});s.value=this.currentGroupId;}
	updateGroupStats(){const friends=this.getCurrentGroupFriends();const expenses=this.getCurrentGroupExpenses();const total=expenses.reduce((sum,e)=>sum+e.amount,0);document.getElementById('group-friends-count').textContent=friends.length;document.getElementById('group-expenses-count').textContent=expenses.length;document.getElementById('group-total-amount').textContent=total.toFixed(2);}
	getCurrentGroupFriends(){return this.friends.filter(f=>f.groupId===this.currentGroupId);} getCurrentGroupExpenses(){return this.expenses.filter(e=>e.groupId===this.currentGroupId);} 
	setupEventListeners(){document.getElementById('choose-folder-btn').addEventListener('click',()=>this.chooseFolderLocation());document.getElementById('save-data-btn').addEventListener('click',()=>this.saveToFile());document.getElementById('load-data-btn').addEventListener('click',()=>this.loadFromFile());document.getElementById('auto-save-toggle').addEventListener('change',e=>{this.autoSaveEnabled=e.target.checked;this.updateStorageUI();});document.getElementById('add-group-btn').addEventListener('click',()=>this.addGroup());document.getElementById('new-group-name').addEventListener('keypress',e=>{if(e.key==='Enter'){e.preventDefault();this.addGroup();}});document.getElementById('group-selector').addEventListener('change',e=>this.switchGroup(e.target.value));document.getElementById('delete-group-btn').addEventListener('click',()=>this.deleteCurrentGroup());document.getElementById('add-friend-btn').addEventListener('click',()=>this.addFriend());document.getElementById('friend-name').addEventListener('keypress',e=>{if(e.key==='Enter'){e.preventDefault();this.addFriend();}});document.getElementById('expense-form').addEventListener('submit',e=>{e.preventDefault();this.addExpense();});document.querySelectorAll('input[name="split-type"]').forEach(r=>r.addEventListener('change',()=>this.updateSplitDetails()));document.getElementById('expense-amount').addEventListener('input',()=>this.updateSplitDetails());document.getElementById('export-expenses-btn').addEventListener('click',()=>this.exportExpenses());document.getElementById('export-balances-btn').addEventListener('click',()=>this.exportBalanceSummary());document.getElementById('export-expense-summary-btn').addEventListener('click',()=>this.exportExpenseSummary());document.getElementById('export-all-data-btn').addEventListener('click',()=>this.exportAllData());document.getElementById('filter-group').addEventListener('change',()=>this.displayExpenses());document.getElementById('filter-category').addEventListener('change',()=>this.displayExpenses());document.getElementById('filter-date-range').addEventListener('change',()=>this.displayExpenses());document.getElementById('import-data-btn').addEventListener('click',()=>document.getElementById('import-file-input').click());document.getElementById('import-file-input').addEventListener('change',e=>this.importData(e.target.files[0]));document.getElementById('clear-all-expenses-btn').addEventListener('click',()=>this.clearAllExpenses());document.getElementById('confirm-settlement').addEventListener('click',()=>this.confirmSettlement());document.getElementById('cancel-settlement').addEventListener('click',()=>this.hideSettlementModal());document.querySelector('.close-modal').addEventListener('click',()=>this.hideSettlementModal());}
	setTodayDate(){const today=new Date().toISOString().split('T')[0];document.getElementById('expense-date').value=today;}
	addFriend(){const input=document.getElementById('friend-name');const name=input.value.trim();if(!name){this.showNotification('Please enter a friend\'s name','error');return;}const existing=this.getCurrentGroupFriends();if(existing.some(f=>f.name.toLowerCase()===name.toLowerCase())){this.showNotification('Friend already exists in this group','error');return;}const friend={id:Date.now(),name,groupId:this.currentGroupId,createdAt:new Date()};this.friends.push(friend);this.saveToStorage();input.value='';this.displayFriends();this.updatePaidByOptions();this.updateSplitDetails();this.updateGroupStats();this.showNotification(`${name} added to ${this.getCurrentGroupName()}!`,'success');}
	getCurrentGroupName(){const g=this.groups.find(g=>g.id===this.currentGroupId);return g?g.name:'Default Group';}
	removeFriend(id){const f=this.friends.find(x=>x.id===id);if(!f)return;const hasExp=this.expenses.some(e=>e.paidBy===id||Object.keys(e.splits).includes(id.toString()));if(hasExp){this.showNotification('Cannot remove friend with existing expenses','error');return;}if(confirm(`Remove ${f.name} from the group?`)){this.friends=this.friends.filter(x=>x.id!==id);this.saveToStorage();this.displayFriends();this.updatePaidByOptions();this.updateSplitDetails();this.showNotification(`${f.name} removed successfully!`,'success');}}
	displayFriends(){const list=document.getElementById('friends-list');const friends=this.getCurrentGroupFriends();if(friends.length===0){list.innerHTML=`<div class="empty-state"><i class="fas fa-user-plus"></i><p>Add friends to ${this.getCurrentGroupName()}</p></div>`;return;}list.innerHTML=friends.map(f=>`<div class="friend-card"><div class="friend-info"><div class="friend-avatar">${f.name.charAt(0).toUpperCase()}</div><div class="friend-name-text">${f.name}</div></div><button class="btn btn-danger btn-small" onclick="splitter.removeFriend(${f.id})"><i class="fas fa-times"></i></button></div>`).join('');}
	updatePaidByOptions(){const sel=document.getElementById('expense-paidby');sel.innerHTML='<option value="">Select who paid</option>';this.getCurrentGroupFriends().forEach(f=>{const o=document.createElement('option');o.value=f.id;o.textContent=f.name;sel.appendChild(o);});}
	updateSplitDetails(){const friends=this.getCurrentGroupFriends();if(friends.length===0){document.getElementById('split-details').innerHTML=`<div class=\"empty-state\"><i class=\"fas fa-users\"></i><p>Add friends to ${this.getCurrentGroupName()} first</p></div>`;return;}const splitType=document.querySelector('input[name="split-type"]:checked').value;const total=parseFloat(document.getElementById('expense-amount').value)||0;const container=document.getElementById('split-details');let html='<h4>Split breakdown:</h4>';if(splitType==='equal'){const each=total/friends.length;html+=friends.map(fr=>`<div class=\"split-item\"><span class=\"friend-name\">${fr.name}</span><span class=\"split-amount\">₹${each.toFixed(2)}</span></div>`).join('');}else if(splitType==='percentage'){html+=friends.map(fr=>`<div class=\"split-item\"><span class=\"friend-name\">${fr.name}</span><input type=\"number\" class=\"split-input\" data-friend-id=\"${fr.id}\" placeholder=\"%\" min=\"0\" max=\"100\" step=\"0.1\"><span class=\"split-amount\" id=\"amount-${fr.id}\">₹0.00</span></div>`).join('');html+=`<div class=\"split-item\" style=\"border-top:2px solid #ff9a9e;font-weight:bold;\"><span>Total Percentage:</span><span id=\"total-percentage\">0%</span><span class=\"split-amount\">₹${total.toFixed(2)}</span></div>`;}else if(splitType==='custom'){html+=friends.map(fr=>`<div class=\"split-item\"><span class=\"friend-name\">${fr.name}</span><input type=\"number\" class=\"split-input\" data-friend-id=\"${fr.id}\" placeholder=\"Amount\" min=\"0\" step=\"0.01\"><span class=\"split-amount\">₹</span></div>`).join('');html+=`<div class=\"split-item\" style=\"border-top:2px solid #ff9a9e;font-weight:bold;\"><span>Total Split:</span><span id=\"total-split-amount\">₹0.00</span><span class=\"split-amount\">₹${total.toFixed(2)}</span></div>`;}container.innerHTML=html;if(splitType==='percentage'){document.querySelectorAll('.split-input').forEach(inp=>inp.addEventListener('input',()=>this.calculatePercentageSplits(total)));}else if(splitType==='custom'){document.querySelectorAll('.split-input').forEach(inp=>inp.addEventListener('input',()=>this.calculateCustomSplits()));}}
	calculatePercentageSplits(total){let tp=0;document.querySelectorAll('.split-input').forEach(inp=>{const p=parseFloat(inp.value)||0;const id=inp.dataset.friendId;const amt=(total*p)/100;document.getElementById(`amount-${id}`).textContent=`₹${amt.toFixed(2)}`;tp+=p;});const el=document.getElementById('total-percentage');el.textContent=`${tp.toFixed(1)}%`;el.style.color=tp===100?'#28a745':'#dc3545';}
	calculateCustomSplits(){let ts=0;document.querySelectorAll('.split-input').forEach(i=>{ts+=parseFloat(i.value)||0;});const el=document.getElementById('total-split-amount');el.textContent=`₹${ts.toFixed(2)}`;const original=parseFloat(document.getElementById('expense-amount').value)||0;el.style.color=Math.abs(ts-original)<0.01?'#28a745':'#dc3545';}
	addExpense(){const description=document.getElementById('expense-description').value.trim();const amount=parseFloat(document.getElementById('expense-amount').value);const paidById=parseInt(document.getElementById('expense-paidby').value);const date=document.getElementById('expense-date').value;const groupId=document.getElementById('expense-group').value;const category=document.getElementById('expense-category').value;const splitType=document.querySelector('input[name="split-type"]:checked').value;if(!description||!amount||!paidById||!date||!groupId){this.showNotification('Please fill in all required fields','error');return;}if(amount<=0){this.showNotification('Amount must be greater than 0','error');return;}if(this.getCurrentGroupFriends().length===0){this.showNotification('Add friends to the group first','error');return;}const splits=this.calculateSplits(splitType,amount);if(!splits)return;const expense={id:Date.now(),description,amount,paidBy:paidById,date:new Date(date),groupId,category:category||'miscellaneous',splitType,splits,createdAt:new Date()};this.expenses.push(expense);this.saveToStorage();this.clearExpenseForm();this.displayExpenses();this.updateBalanceSummary();this.updateSettlementSuggestions();this.updateGroupStats();this.showNotification('Expense added and split successfully!','success');}
	calculateSplits(type,total){const splits={};const friends=this.getCurrentGroupFriends();if(type==='equal'){const each=total/friends.length;friends.forEach(f=>splits[f.id]=each);}else if(type==='percentage'){let tp=0;document.querySelectorAll('.split-input').forEach(inp=>{const pct=parseFloat(inp.value)||0;tp+=pct;const id=parseInt(inp.dataset.friendId);splits[id]=(total*pct)/100;});if(Math.abs(tp-100)>0.1){this.showNotification('Percentages must add up to 100%','error');return null;}}else if(type==='custom'){let ts=0;document.querySelectorAll('.split-input').forEach(inp=>{const amt=parseFloat(inp.value)||0;ts+=amt;const id=parseInt(inp.dataset.friendId);splits[id]=amt;});if(Math.abs(ts-total)>0.01){this.showNotification('Split amounts must equal the total expense','error');return null;}}return splits;}
	displayExpenses(){const history=document.getElementById('expenses-history');const filtered=this.getFilteredExpenses();if(filtered.length===0){history.innerHTML='<div class="empty-state"><i class="fas fa-receipt"></i><p>No expenses found matching your filters</p></div>';return;}const sorted=[...filtered].sort((a,b)=>new Date(b.date)-new Date(a.date));history.innerHTML=sorted.map(exp=>{const paidBy=this.friends.find(f=>f.id===exp.paidBy);const group=this.groups.find(g=>g.id===exp.groupId);const splitSummary=Object.entries(exp.splits).map(([fid,amt])=>{const fr=this.friends.find(f=>f.id===parseInt(fid));return fr?`${fr.name}: ₹${amt.toFixed(2)}`:'';}).filter(Boolean).join(', ');return `<div class=\"expense-item\"><div class=\"expense-header\"><div class=\"expense-title\">${exp.description}</div><div class=\"expense-amount-large\">₹${exp.amount.toFixed(2)}</div></div><div class=\"expense-meta\"><div class=\"meta-item\"><i class=\"fas fa-calendar\"></i>${this.formatDate(exp.date)}</div><div class=\"meta-item\"><i class=\"fas fa-layer-group\"></i>${group?group.name:'Unknown Group'}</div><div class=\"meta-item\"><i class=\"fas fa-tag\"></i>${this.getCategoryName(exp.category)}</div><div class=\"meta-item\"><i class=\"fas fa-user\"></i>Paid by ${paidBy?paidBy.name:'Unknown'}</div><div class=\"meta-item\"><i class=\"fas fa-scissors\"></i>${this.getSplitTypeText(exp.splitType)}</div></div><div class=\"splits-summary\"><div class=\"splits-title\">Split Details:</div><div class=\"split-list\">${splitSummary}</div></div></div>`;}).join('');}
	getFilteredExpenses(){let f=[...this.expenses];const gf=document.getElementById('filter-group').value;if(gf==='current'){f=f.filter(e=>e.groupId===this.currentGroupId);}else if(gf!=='all'){f=f.filter(e=>e.groupId===gf);}const cf=document.getElementById('filter-category').value;if(cf!=='all'){f=f.filter(e=>e.category===cf);}const dr=document.getElementById('filter-date-range').value;if(dr!=='all'){const now=new Date();let start; if(dr==='week'){start=new Date(now.getTime()-7*24*60*60*1000);}else if(dr==='month'){start=new Date(now.getTime()-30*24*60*60*1000);} if(start){f=f.filter(e=>new Date(e.date)>=start);} }return f;}
	getSplitTypeText(t){return {equal:'Split Equally',percentage:'By Percentage',custom:'Custom Amounts'}[t]||t;}
	updateBalanceSummary(){const balances=this.calculateBalances();const container=document.getElementById('balance-summary');const entries=Object.entries(balances).filter(([_,b])=>Math.abs(b)>0.01);if(entries.length===0){container.innerHTML='<div class="empty-state"><i class="fas fa-balance-scale"></i><p>All balances are settled! 🎉</p></div>';return;}container.innerHTML=entries.map(([fid,b])=>{const friend=this.friends.find(f=>f.id===parseInt(fid));if(!friend)return'';const owed=b>0;const amt=Math.abs(b);return `<div class=\"balance-card ${owed?'owed':'owes'}\"><div class=\"balance-header\"><div class=\"balance-icon ${owed?'owed':'owes'}\"><i class=\"fas fa-${owed?'arrow-up':'arrow-down'}\"></i></div><div class=\"balance-title\">${friend.name}</div></div><div class=\"balance-amount ${owed?'owed':'owes'}\">₹${amt.toFixed(2)}</div><div class=\"balance-details\">${owed?'Should receive':'Owes to others'}</div></div>`;}).join('');}
	calculateBalances(){const balances={};this.getCurrentGroupFriends().forEach(f=>balances[f.id]=0);this.getCurrentGroupExpenses().forEach(exp=>{if(balances[exp.paidBy]!==undefined)balances[exp.paidBy]+=exp.amount;Object.entries(exp.splits).forEach(([fid,amt])=>{const id=parseInt(fid);if(balances[id]!==undefined)balances[id]-=amt;});});this.settlements.filter(s=>{const p=this.friends.find(f=>f.id===s.payer);const y=this.friends.find(f=>f.id===s.payee);return p?.groupId===this.currentGroupId&&y?.groupId===this.currentGroupId;}).forEach(s=>{if(balances[s.payer]!==undefined)balances[s.payer]-=s.amount;if(balances[s.payee]!==undefined)balances[s.payee]+=s.amount;});return balances;}
	updateSettlementSuggestions(){const balances=this.calculateBalances();const cont=document.getElementById('settlement-suggestions');const debtors=[];const creditors=[];Object.entries(balances).forEach(([id,b])=>{if(b<-0.01)debtors.push({id:parseInt(id),amount:Math.abs(b)});else if(b>0.01)creditors.push({id:parseInt(id),amount:b});});if(debtors.length===0&&creditors.length===0){cont.innerHTML='<div class="empty-state"><i class="fas fa-handshake"></i><p>All debts are settled! 🎉</p></div>';return;}const suggestions=this.generateSettlementSuggestions(debtors,creditors);cont.innerHTML=suggestions.map(s=>{const payer=this.friends.find(f=>f.id===s.payer);const payee=this.friends.find(f=>f.id===s.payee);return `<div class=\"settlement-card\"><div class=\"settlement-info\"><h4>${payer.name} → ${payee.name}</h4><p>Settle debt</p></div><div class=\"settlement-amount\">₹${s.amount.toFixed(2)}</div><button class=\"btn btn-primary btn-small\" onclick=\"splitter.showSettlementModal(${s.payer},${s.payee},${s.amount})\"><i class=\"fas fa-handshake\"></i> Settle</button></div>`;}).join('');}
	generateSettlementSuggestions(debtors,creditors){const out=[];const d=[...debtors];const c=[...creditors];while(d.length>0&&c.length>0){const db=d[0];const cr=c[0];const amt=Math.min(db.amount,cr.amount);out.push({payer:db.id,payee:cr.id,amount:amt});db.amount-=amt;cr.amount-=amt;if(db.amount<0.01)d.shift();if(cr.amount<0.01)c.shift();}return out;}
	showSettlementModal(payer,payee,amount){const pf=this.friends.find(f=>f.id===payer);const yf=this.friends.find(f=>f.id===payee);document.getElementById('settlement-details').textContent=`${pf.name} will pay ₹${amount.toFixed(2)} to ${yf.name}`;this.pendingSettlement={payer,payee,amount};document.getElementById('settlement-modal').classList.remove('hidden');}
	hideSettlementModal(){document.getElementById('settlement-modal').classList.add('hidden');this.pendingSettlement=null;}
	confirmSettlement(){if(!this.pendingSettlement)return;const s={id:Date.now(),...this.pendingSettlement,date:new Date(),createdAt:new Date()};this.settlements.push(s);this.saveToStorage();this.updateBalanceSummary();this.updateSettlementSuggestions();this.hideSettlementModal();const pf=this.friends.find(f=>f.id===s.payer);const yf=this.friends.find(f=>f.id===s.payee);this.showNotification(`Settlement recorded: ${pf.name} paid ${yf.name} ₹${s.amount.toFixed(2)}`,'success');}
	formatDate(d){return new Date(d).toLocaleDateString('en-IN',{year:'numeric',month:'short',day:'numeric'});} clearExpenseForm(){document.getElementById('expense-form').reset();this.setTodayDate();document.getElementById('expense-group').value=this.currentGroupId;document.querySelector('input[name="split-type"][value="equal"]').checked=true;this.updateSplitDetails();}
	exportExpenses(){if(this.expenses.length===0){this.showNotification('No expenses to export','error');return;}const csv=this.generateExpensesCSV();this.downloadCSV(csv,`shared_expenses_${new Date().toISOString().split('T')[0]}.csv`);this.showNotification('Expenses exported successfully!','success');}
	exportBalanceSummary(){const balances=this.calculateBalances();if(!Object.values(balances).some(b=>Math.abs(b)>0.01)){this.showNotification('No balances to export - everyone is settled!','error');return;}const csv=this.generateBalanceSummaryCSV(balances);this.downloadCSV(csv,`balance_summary_${new Date().toISOString().split('T')[0]}.csv`);this.showNotification('Balance summary exported successfully!','success');}
	exportExpenseSummary(){if(this.expenses.length===0){this.showNotification('No expenses to export','error');return;}const csv=this.generateExpenseSummaryCSV();this.downloadCSV(csv,`expense_summary_${new Date().toISOString().split('T')[0]}.csv`);this.showNotification('Expense summary exported successfully!','success');}
	exportAllData(){if(this.friends.length===0&&this.expenses.length===0){this.showNotification('No data to export','error');return;}const all={exportDate:new Date().toISOString(),friends:this.friends,expenses:this.expenses,settlements:this.settlements,balances:this.calculateBalances(),summary:this.generateDataSummary()};const json=JSON.stringify(all,null,2);const blob=new Blob([json],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`expense_splitter_backup_${new Date().toISOString().split('T')[0]}.json`;document.body.appendChild(a);a.click();document.body.removeChild(a);URL.revokeObjectURL(url);this.showNotification('Complete data backup exported successfully!','success');}
	importData(file){if(!file){this.showNotification('Please select a file to import','error');return;}if(!file.name.endsWith('.json')){this.showNotification('Please select a valid JSON backup file','error');return;}const reader=new FileReader();reader.onload=e=>{try{const data=JSON.parse(e.target.result);if(!this.validateImportedData(data)){this.showNotification('Invalid backup file format','error');return;}if(!confirm(`Import data from ${file.name}? This will replace current data.`))return;this.createAutomaticBackup();this.friends=data.friends||[];this.expenses=data.expenses||[];this.settlements=data.settlements||[];this.expenses.forEach(x=>{x.date=new Date(x.date);x.createdAt=new Date(x.createdAt);});this.settlements.forEach(x=>{x.date=new Date(x.date);x.createdAt=new Date(x.createdAt);});this.friends.forEach(x=>{x.createdAt=new Date(x.createdAt);});this.saveToStorage();this.displayFriends();this.updatePaidByOptions();this.displayExpenses();this.updateBalanceSummary();this.updateSettlementSuggestions();this.updateSplitDetails();this.showNotification('Data imported successfully!','success');}catch(err){console.error('Error importing data:',err);this.showNotification('Error reading backup file. File may be corrupted.','error');}};reader.onerror=()=>this.showNotification('Error reading file','error');reader.readAsText(file);document.getElementById('import-file-input').value='';}
	validateImportedData(d){return d&&((d.friends!==undefined&&d.expenses!==undefined)||(Array.isArray(d.friends)||Array.isArray(d.expenses)));}
	generateExpensesCSV(){const headers=['Date','Group','Category','Description','Amount','Paid By','Split Type','Friend','Share Amount'];const rows=[];this.expenses.forEach(exp=>{const paidBy=this.friends.find(f=>f.id===exp.paidBy);const group=this.groups.find(g=>g.id===exp.groupId);Object.entries(exp.splits).forEach(([fid,amt])=>{const fr=this.friends.find(f=>f.id===parseInt(fid));rows.push([this.formatDate(exp.date),group?group.name:'Unknown Group',this.getCategoryName(exp.category),exp.description,exp.amount.toFixed(2),paidBy?paidBy.name:'Unknown',this.getSplitTypeText(exp.splitType),fr?fr.name:'Unknown',amt.toFixed(2)]);});});return [headers,...rows].map(r=>r.map(f=>`"${f}"`).join(',')).join('\n');}
	generateExpenseSummaryCSV(){const headers=['Friend Name','Group','Total Paid','Total Share','Net Balance','Number of Expenses'];const rows=[];rows.push(['Expense Summary Report','','','','',`Generated on: ${new Date().toLocaleString()}`]);rows.push(['','','','','','']);const person={};this.expenses.forEach(exp=>{const group=this.groups.find(g=>g.id===exp.groupId);const groupName=group?group.name:'Unknown Group';Object.entries(exp.splits).forEach(([fid,share])=>{const fr=this.friends.find(f=>f.id===parseInt(fid));if(!fr)return;const key=`${fr.name}_${groupName}`;if(!person[key])person[key]={name:fr.name,group:groupName,totalPaid:0,totalShare:0,expenseCount:0};person[key].totalShare+=share;person[key].expenseCount+=1;if(exp.paidBy===parseInt(fid))person[key].totalPaid+=exp.amount;});});Object.values(person).forEach(p=>{const net=p.totalPaid-p.totalShare;rows.push([p.name,p.group,`₹${p.totalPaid.toFixed(2)}`,`₹${p.totalShare.toFixed(2)}`,`₹${net.toFixed(2)}`,p.expenseCount.toString()]);});rows.push(['','','','','','']);rows.push(['GROUP SUMMARIES:','','','','','']);const gsum={};this.expenses.forEach(exp=>{const group=this.groups.find(g=>g.id===exp.groupId);const gName=group?group.name:'Unknown Group';if(!gsum[gName])gsum[gName]={totalAmount:0,expenseCount:0,uniquePeople:new Set()};gsum[gName].totalAmount+=exp.amount;gsum[gName].expenseCount+=1;Object.keys(exp.splits).forEach(fid=>{const fr=this.friends.find(f=>f.id===parseInt(fid));if(fr)gsum[gName].uniquePeople.add(fr.name);});});Object.entries(gsum).forEach(([gName,s])=>{rows.push([`${gName} Total`,gName,`₹${s.totalAmount.toFixed(2)}`,`${s.expenseCount} expenses`,`${s.uniquePeople.size} people`,'']);});return [headers,...rows].map(r=>r.map(f=>`"${f}"`).join(',')).join('\n');}
	getCategoryName(cat){return {food:'Food & Dining',accommodation:'Accommodation',transportation:'Transportation',entertainment:'Entertainment',groceries:'Groceries',utilities:'Utilities',miscellaneous:'Miscellaneous'}[cat]||'Miscellaneous';}
	generateBalanceSummaryCSV(balances){const headers=['Friend Name','Balance Amount','Status','Details'];const rows=[];rows.push(['Balance Summary Report','','',`Generated on: ${new Date().toLocaleString()}`]);rows.push(['','','','']);Object.entries(balances).forEach(([fid,b])=>{const fr=this.friends.find(f=>f.id===parseInt(fid));if(!fr)return;const abs=Math.abs(b);if(abs<0.01)return;const status=b>0?'Should Receive':'Owes Others';const details=b>0?`${fr.name} should receive ₹${abs.toFixed(2)} from others`:`${fr.name} owes ₹${abs.toFixed(2)} to others`;rows.push([fr.name,`₹${abs.toFixed(2)}`,status,details]);});const filtered=Object.fromEntries(Object.entries(balances).filter(([_,b])=>Math.abs(b)>0.01));if(Object.keys(filtered).length>0){rows.push(['','','','']);rows.push(['Settlement Suggestions:','','','']);const debtors=Object.entries(filtered).filter(([_,b])=>b<-0.01).map(([id,b])=>({id:parseInt(id),amount:Math.abs(b)}));const creditors=Object.entries(filtered).filter(([_,b])=>b>0.01).map(([id,b])=>({id:parseInt(id),amount:b}));const suggestions=this.generateSettlementSuggestions(debtors,creditors);suggestions.forEach((s,i)=>{const pf=this.friends.find(f=>f.id===s.payer);const yf=this.friends.find(f=>f.id===s.payee);rows.push([`Settlement ${i+1}`,`₹${s.amount.toFixed(2)}`,'Payment Needed',`${pf.name} should pay ${yf.name} ₹${s.amount.toFixed(2)}`]);});}return [headers,...rows].map(r=>r.map(f=>`"${f}"`).join(',')).join('\n');}
	generateDataSummary(){const balances=this.calculateBalances();const totalExpenses=this.expenses.reduce((s,e)=>s+e.amount,0);const totalSettlements=this.settlements.reduce((s,e)=>s+e.amount,0);return{totalFriends:this.friends.length,totalExpenses:this.expenses.length,totalExpenseAmount:totalExpenses,totalSettlements:this.settlements.length,totalSettlementAmount:totalSettlements,outstandingBalances:Object.values(balances).filter(b=>Math.abs(b)>0.01).length,lastUpdate:new Date().toISOString()};}
	downloadCSV(content,filename){const blob=new Blob([content],{type:'text/csv;charset=utf-8;'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();document.body.removeChild(a);URL.revokeObjectURL(url);} 
	clearAllExpenses(){if(this.expenses.length===0&&this.settlements.length===0){this.showNotification('No data to clear','error');return;}if(confirm('Delete ALL expenses and settlements? This cannot be undone.')){this.expenses=[];this.settlements=[];this.saveToStorage();this.displayExpenses();this.updateBalanceSummary();this.updateSettlementSuggestions();this.showNotification('All data cleared successfully!','success');}}
	saveToStorage(){if(this.autoSaveEnabled&&this.fileStorage.isReady())this.saveToFile();try{localStorage.setItem('splitter_groups',JSON.stringify(this.groups));localStorage.setItem('splitter_friends',JSON.stringify(this.friends));localStorage.setItem('splitter_expenses',JSON.stringify(this.expenses));localStorage.setItem('splitter_settlements',JSON.stringify(this.settlements));localStorage.setItem('splitter_currentGroup',this.currentGroupId);const metadata={lastSaved:new Date().toISOString(),dataVersion:'2.0',totalRecords:{groups:this.groups.length,friends:this.friends.length,expenses:this.expenses.length,settlements:this.settlements.length},checksum:this.generateDataChecksum()};localStorage.setItem('splitter_metadata',JSON.stringify(metadata));}catch(e){console.error('Error saving to localStorage:',e);if(!this.fileStorage.isReady())this.showNotification('Error saving data. Please choose a folder location.','error');}}
	generateDataChecksum(){return JSON.stringify({friends:this.friends,expenses:this.expenses,settlements:this.settlements}).length.toString();}
	async createAutomaticBackup(){/* optional trimmed in folder copy */}
	loadFromStorage(){try{this.groups=JSON.parse(localStorage.getItem('splitter_groups')||'[]');this.friends=JSON.parse(localStorage.getItem('splitter_friends')||'[]');this.expenses=JSON.parse(localStorage.getItem('splitter_expenses')||'[]');this.settlements=JSON.parse(localStorage.getItem('splitter_settlements')||'[]');this.currentGroupId=localStorage.getItem('splitter_currentGroup')||'default';this.validateDataIntegrity();this.expenses.forEach(e=>{if(e.date)e.date=new Date(e.date);if(e.createdAt)e.createdAt=new Date(e.createdAt);if(!e.groupId)e.groupId='default';if(!e.category)e.category='miscellaneous';});this.settlements.forEach(s=>{if(s.date)s.date=new Date(s.date);if(s.createdAt)s.createdAt=new Date(s.createdAt);});this.friends.forEach(f=>{if(f.createdAt)f.createdAt=new Date(f.createdAt);if(!f.groupId)f.groupId='default';});this.groups.forEach(g=>{if(g.createdAt)g.createdAt=new Date(g.createdAt);});}catch(e){console.error('Error loading from localStorage:',e);this.groups=[];this.friends=[];this.expenses=[];this.settlements=[];this.currentGroupId='default';}}
	validateDataIntegrity(){const meta=JSON.parse(localStorage.getItem('splitter_metadata')||'{}');if(meta.checksum){const current=this.generateDataChecksum();if(current!==meta.checksum)console.warn('Data integrity check failed.');}if(!Array.isArray(this.friends))this.friends=[];if(!Array.isArray(this.expenses))this.expenses=[];if(!Array.isArray(this.settlements))this.settlements=[];this.friends=this.friends.filter(f=>f&&f.id&&f.name);this.expenses=this.expenses.filter(e=>e&&e.id&&e.amount&&e.paidBy);this.settlements=this.settlements.filter(s=>s&&s.id&&s.payer&&s.payee&&s.amount);}
	showNotification(msg,type){const n=document.getElementById('notification');n.textContent=msg;n.className=`notification ${type}`;n.classList.remove('hidden');setTimeout(()=>{n.classList.add('show');},100);setTimeout(()=>{n.classList.remove('show');setTimeout(()=>n.classList.add('hidden'),300);},4000);}
}

let splitter;document.addEventListener('DOMContentLoaded',()=>{splitter=new ExpenseSplitter();splitter.updateCategoryChart&&splitter.updateCategoryChart();});
document.addEventListener('DOMContentLoaded',()=>{const hasData=localStorage.getItem('splitter_friends');if(!hasData){const sample=[{id:1,name:'Alice',createdAt:new Date()},{id:2,name:'Bob',createdAt:new Date()},{id:3,name:'Charlie',createdAt:new Date()}];localStorage.setItem('splitter_friends',JSON.stringify(sample));}});
ExpenseSplitter.prototype.updateCategoryChart=function(){const canvas=document.getElementById('group-category-chart');if(!canvas)return;const ctx=canvas.getContext('2d');const expenses=this.getCurrentGroupExpenses();const totals={};expenses.forEach(e=>{const c=e.category||'miscellaneous';totals[c]=(totals[c]||0)+e.amount;});const cats=Object.keys(totals);const vals=Object.values(totals);if(this.categoryChart)this.categoryChart.destroy();if(vals.length===0){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.font='16px Segoe UI';ctx.fillStyle='#666';ctx.textAlign='center';ctx.fillText('No category data yet',canvas.width/2,canvas.height/2);return;}const colorMap={rent:'#FF6384',groceries:'#36A2EB',utilities:'#FFCE56',transportation:'#4BC0C0',food:'#9966FF',entertainment:'#FF9F40',healthcare:'#8BC34A',education:'#795548',miscellaneous:'#C9CBCF'};const colors=cats.map(c=>colorMap[c]||'#888');this.categoryChart=new Chart(ctx,{type:'doughnut',data:{labels:cats.map(c=>this.getCategoryName(c)),datasets:[{data:vals,backgroundColor:colors,borderWidth:2,borderColor:'#fff'}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom',labels:{usePointStyle:true}},tooltip:{callbacks:{label:ctx=>{const total=ctx.dataset.data.reduce((a,b)=>a+b,0);const pct=((ctx.parsed/total)*100).toFixed(1);return `${ctx.label}: ₹${ctx.parsed.toFixed(2)} (${pct}%)`;}}}}});};
['displayExpenses','switchGroup','addExpense'].forEach(method=>{const orig=ExpenseSplitter.prototype[method];ExpenseSplitter.prototype[method]=function(...a){const r=orig.apply(this,a);this.updateCategoryChart();return r;};});
// Recurring logic trimmed for folder variant; can be copied if needed.
